version: '2'
services:
  db:
    image: postgres
  web: 
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/deeposmorg
    ports:
      - "8000:8000"
    depends_on:
      - db