language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran # required for `pip install scipy` to succeed
  
# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: python -m doctest *.py # Change to `doctest -v *.py` for more verbose logs
